tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: Nutanixshell
  template_author: Anonymous
  template_version: 0.1.0
  template_icon: shell-icon.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:

  vendor.resource.Nutanix_Clone_From_VM:
    derived_from: cloudshell.nodes.CustomDeploymentOption

    properties:
        Cloned VM UUID:
            type: string
            description: "The id of the VM or Snapshot the App will be cloned from."
            default: ''
            tags: [user_input, editable_only_in_app_template]
        Storage Container UUID:
            type: string
            description: "UUID of the storage container on which the customization config iso files should be created. Must be provided when cluster has more than one container."
            default: ''
            tags: [user_input, editable_only_in_app_template]


    artifacts:
      icon:
        file: shell-icon.png
        type: tosca.artifacts.File